Add full support for acpi
lambdalisue/battery.vim pull request #12
Opened 2021-03-10 07:56 UTC by Freed-Wu

Not all acpi client of linux use `/sys/class/power_supply/AC*/online` to show
if the battery is charging (at least my distribution).
`/sys/class/power_supply/BAT*/status` can did the same function.

after this change, now it can work in my linux.

![Screenshot from 2021-03-10 15-40-12](https://user-images.githubusercontent.com/32936898/110595546-15d2c700-81b9-11eb-8aad-01dc1be6a0ba.png)

And not only `/sys/class/power_supply/BAT*/status`, refer <https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L1326>:

```sh
      local -a bats=( /sys/class/power_supply/(CMB*|BAT*|battery)/(FN) )
```

for example, my android use `/sys/class/power_supply/battery/status`
not `/sys/class/power_supply/BAT*/status`.

the backend can also work for android which work for root user (in android,
only root can have privilege to read `/sys`). for android work for non-root
user, the <https://github.com/lambdalisue/battery.vim/issues/9> is also a
valid substitution.

thanks for your review.

2021-03-10 08:31 UTC, Freed-Wu commented
oops! i found although my linux don't have
`/sys/class/power_supply/AC*/online`, however,
`/sys/class/power_supply/ADP*/online` exists. and in my android, 
`/sys/class/power_supply/ac/online`, `/sys/class/power_supply/usb/online`
and `/sys/class/power_supply/pc_port/online` exist. so the
`/sys/class/power_supply/*/online` only display the method of charging: use
usb, ac charger, dc charger, not if the device is charging. so i advice use
`/sys/class/power_supply/(CMB*|BAT*|battery)/status` to replace
`/sys/class/power_supply/*/online`.

2021-03-10 08:32 UTC, Freed-Wu commented
>  so i advice use
> /sys/class/power_supply/(CMB*|BAT*|battery)/status to replace
> /sys/class/power_supply/*/online.

because we just only wanna know if the battery is charging, not the method of
charging.

2021-03-10 09:21 UTC, Freed-Wu commented
<https://github.com/lambdalisue/battery.vim/blob/master/autoload/battery/backend/linux.vim#L2>
```vim
let s:Job = vital#battery#import('System.Job')
```

`s:Job` is not be used in this script. what is its use? can this line be
deleted?

2021-03-10 13:29 UTC, lambdalisue commented
I'll check it in this weekend. Ping me if I've not replied even after the weekend.

2021-03-14 09:00 UTC, lambdalisue commented
https://github.com/lambdalisue/battery.vim/pull/12#issuecomment-795082243

Well... What is the conclusion? It seems the code tried to glob from `/sys/class/power_supply/{CMD*,BAT*,battery}/{status, capacity}`. I'd like to review the final code.

Additionally, do you have documentation about each path? It seems `/sys/class/power_supply/BAT*/online` does not exist (https://github.com/lambdalisue/battery.vim/issues/7)

https://github.com/lambdalisue/battery.vim/pull/12#issuecomment-795137974

Yes, it's not used here.

2021-03-14 11:02 UTC, Freed-Wu commented
> Yes, it's not used here.

thanks. i have deleted this line which is not used.

> It seems the code tried to glob

you are right. now i have rewrited it.

> do you have documentation about each path

According to
<https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L1324-L1326>

```sh
    Linux|Android)
      # See https://sourceforge.net/projects/acpiclient.
      local -a bats=( /sys/class/power_supply/(CMB*|BAT*|battery)/(FN) )
```

the original documents can be found in
<https://sourceforge.net/projects/acpiclient>.

2021-03-14 13:31 UTC, lambdalisue requested changes

2021-03-14 13:31 UTC, lambdalisue commented on autoload/battery/backend/linux.vim
> +let s:bat_capacity = get(s:bat_files, 1, '')
`s:bat_capacity` might get wrong path when there are several match on the first pattern.

Assume that you have

```
├── a
│   ├── a
│   ├── b
│   └── c
└── b
    ├── a
    ├── b
    └── c
```

And then

```
:echo glob('./{a,b}/{a,b}', 0, 1)
['./a/a/', './a/b/', './b/a/', './b/b/']
```

Probably, it's better to use glob in each variables like

```suggestion
let s:bat_status = get(glob('/sys/class/power_supply/{CMD*,BAT*,battery}/status', 0, 1), 0, '')
let s:bat_capacity = get(glob('/sys/class/power_supply/{CMD*,BAT*,battery}/capacity', 0, 1), 0, '')
```

2021-03-14 13:53 UTC, Freed-Wu commented
great. now it can work.

2021-03-14 14:04 UTC, lambdalisue approved these changes

2021-03-14 14:04 UTC, merged

2021-03-14 14:04 UTC, lambdalisue commented
👍