Add support for termux
lambdalisue/battery.vim pull request #13
Opened 2021-03-10 10:27 UTC by Freed-Wu

![Screenshot-20210310180229-1366x768](https://user-images.githubusercontent.com/32936898/110614885-c5199900-81cd-11eb-8254-6fce46546de7.png)

`termux-api` maybe hang in some conditions.
so wait <https://github.com/termux/termux-api/issues/402> to be fixed may be
better.

2021-03-10 10:29 UTC, Freed-Wu commented
i forgot to write `Fix #9` in the commit message... Sorry!

2021-03-10 13:29 UTC, lambdalisue commented
I'll check it in this weekend. Ping me if I've not replied even after the weekend.

2021-03-14 08:51 UTC, lambdalisue requested changes

2021-03-14 08:51 UTC, lambdalisue commented on autoload/battery/backend/termux.vim
> +endfunction
`system()` should not be used. Use `System.Job` instead.

You can find the documentation here
https://github.com/lambdalisue/vital-Whisky/blob/master/doc/Vital/System/Job.txt

2021-03-14 13:54 UTC, Freed-Wu commented
![Screenshot from 2021-03-14 21-40-31](https://user-images.githubusercontent.com/32936898/111071159-d1745d80-850f-11eb-9b88-f2e663909db7.png)

you are right. now it can work.

2021-03-14 14:06 UTC, lambdalisue approved these changes

2021-03-14 14:06 UTC, merged

2021-03-14 14:06 UTC, lambdalisue commented
👍